import express from 'express';
import ArticleController from '../controllers/articleController';
import CommentController from '../controllers/commentController';
import auth from '../middlewares/auth';
import admin from '../middlewares/admin';
const router = express.Router();

const articleController = new ArticleController();
const commentController = new CommentController();
router.post('/articles', auth, articleController.createArticle);
router.patch('/articles/:articleId', auth, articleController.updateArticle);
router.delete('/articles/:articleId', auth, articleController.deleteArticle);
router.post('/articles/:articleId/comments', auth, commentController.commentArticle);
router.get('/feeds', articleController.getFeeds);
router.get('/articles/:articleId', articleController.getSpecificArticle);
router.patch('/articles/:articleId/flag', auth, articleController.flagArticle);
router.patch('/comments/:commentId/flag', auth, commentController.flagComment);
router.delete('/articles/:articleId/delete', admin, articleController.deleteFlaggedArticle);
router.delete('/comments/:commentId/delete', admin, commentController.deleteFlaggedComment);
export default router;
